name: Terraform Manual Control

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose apply or destroy'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0

    - name: Terraform Init
      working-directory: ./JSR/cloud_infrastructure
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}
        ARM_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET:   ${{ secrets.AZURE_CLIENT_SECRET }}
      run: terraform init

    - name: Terraform Plan
      if: ${{ github.event.inputs.action == 'apply' }}
      working-directory: ./JSR/cloud_infrastructure
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}
        ARM_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET:   ${{ secrets.AZURE_CLIENT_SECRET }}
      run: terraform plan -var="sql_password=${{ se_
